// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnjheltlrezscfiejjpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuamhlbHRscmV6c2NmaWVqanBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTE5MTcsImV4cCI6MjA2NDI4NzkxN30.brAyZY-qynZGDR3yyLjlJPt5TlSf_FjVjJkNnRaCgpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);